# Generated by Django 5.1.7 on 2025-03-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_make_en',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_make_ru',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
