# Generated by Django 5.1.7 on 2025-03-11 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_car_make_en_car_car_make_ru_car_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='number_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
    ]
