# Generated by Django 5.1.7 on 2025-03-11 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_phone_number_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_cars', to='car.car'),
        ),
        migrations.AlterField(
            model_name='network',
            name='car_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_cars', to='car.car'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_user', to='car.car'),
        ),
    ]
