# Generated by Django 5.1.7 on 2025-03-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_imagecar_car_alter_network_car_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='spares_name',
            field=models.CharField(blank=True, max_length=76, null=True),
        ),
    ]
